(defsystem "rplaca"
  :description "A Lisp-native Emacs-inspired LLM chat interface"
  :homepage "https://github.com/htayj/rplaca"
  :version "0.1.0"
  :licence "AGPL-3.0-only"
  :depends-on ("lispi" "mcclim" "esa-mcclim" "drei-mcclim"
               "coalton" "alexandria" "drakma" "cl-json" "bordeaux-threads"
               "chipz")
  :serial t
  :components ((:module "src"
                :serial t
                :components ((:file "packages")
                             (:file "listener-dispatch")
                             (:file "legacy-paths")
                             (:file "message")
                             (:file "session")
                             (:file "buffer")
                             (:file "text-utils")
                             (:file "appearance")
                             (:file "appearance-fonts")
                             (:file "appearance-config")
                             (:file "windows")
                             (:file "debug")
                             (:file "package-manager")
                             (:file "appearance-packages")
                             (:file "modelaria-core")
                             (:file "artifactum-core")
                             (:file "media-core")
                             (:file "hooks")
                             (:file "commands")
                             (:file "keymap")
                             (:file "projects")
                             (:file "skills")
                             (:file "templata")
                             (:file "matching-core")
                             (:file "matching")
                             (:file "llm")
                             (:file "session-export")
                             (:file "tools")
                             (:file "safe-reload")
                             (:file "prompt-core")
                             (:file "interop-core")
                             (:file "mcp-bridge-core")
                             (:file "subagents")
                             (:file "compaction")
                             (:file "prompt-runner")
                             (:file "listener-commands-core")
                             (:file "listener-frame")
                             (:file "pipelines")
                             (:file "info")
                             (:file "minibuffer")
                             (:file "prefix")
                             (:file "listener")
                             (:file "font-editor")
                             (:file "crash-report")
                             (:file "crash-report-sbcl")
                             (:file "main")
                             (:file "listener-commands")
                             (:file "mcclim-interface")
                             (:file "reference")
                             (:file "sexed")
                             (:file "slop")
                             (:file "docs")))))

(defsystem "rplaca/tests"
  :description "Tests for RPLACA"
  :licence "AGPL-3.0-only"
  :depends-on ("rplaca" "fiveam")
  :serial t
  :components ((:module "tests"
                :serial t
                 :components ((:file "packages")
                              (:file "listener-dispatch-test")
                              (:file "listener-commands-core-test")
                              (:file "listener-frame-test")
                              (:file "listener-say-test")
                              (:file "listener-await-test")
                              (:file "legacy-path-test")
                              (:file "migration-integration-test")
                              (:file "package-manager-test")
                              (:file "git-package-test")
                              (:file "organa-package-test")
                              (:file "netcons-package-test")
                              (:file "prove-package-test")
                              (:file "subagent-package-test")
                              (:file "templata-package-test")
                              (:file "quaestor-package-test")
                              (:file "modelaria-package-test")
                              (:file "artifactum-package-test")
                              (:file "media-package-test")
                              (:file "codex-image-package-test")
                              (:file "interop-test")
                              (:file "mcp-bridge-package-test")
                              (:file "reference-test")
                              (:file "message-test")
                              (:file "buffer-test")
                              (:file "windows-test")
                              (:file "commands-test")
                              (:file "safe-reload-test")
                              (:file "matching-test")
                              (:file "projects-test")
                              (:file "skills-test")
                              (:file "font-editor-test")
                              (:file "appearance-test")
                              (:file "appearance-font-test")
                              (:file "appearance-config-test")
                              (:file "crash-report-test")
                              (:file "mcclim-interface-test")
                              (:file "sexed-test")
                              (:file "slop-test")
                              (:file "llm-test")
                              (:file "runtime-stability-test")
                              (:file "registry-file-lock-test")
                              (:file "interactive-operation-test")
                              (:file "gui-e2e-test")
                              (:file "keymap-test")
                              (:file "info-test")))))

(defsystem "rplaca/gui-e2e"
  :description "Opt-in GUI E2E suites for RPLACA"
  :licence "AGPL-3.0-only"
  :depends-on ("rplaca")
  :perform (test-op (op c)
             (declare (ignore op))
             (let ((script (merge-pathnames "scripts/run-gui-e2e.sh"
                                            (asdf:system-source-directory c))))
               (dolist (suite '("smoke" "mx" "features" "keybinds" "organa" "quaestor" "reload" "appearance" "stability"))
                 (uiop:run-program
                  (list "sh" (namestring script) "--suite" suite)
                  :directory (asdf:system-source-directory c)
                  :output *standard-output*
                  :error-output *error-output*)))))
