(defpackage #:rplaca/matching-core
  (:use #:coalton #:coalton-prelude)
  (:export
   #:split-query-tokens
   #:fuzzy-token-match-p
   #:fuzzy-match-p
   #:fuzzy-token-positions
   #:fuzzy-match-positions
   #:fuzzy-token-score-or-negative-one
   #:fuzzy-score-or-negative-one))

(defpackage :rplaca
  (:use :cl)
  (:shadowing-import-from :lispi
   #:*tool-working-directory*
   #:*file-read-default-limit*
   #:*find-default-limit*
   #:*grep-default-limit*
   #:*grep-max-file-bytes*
   #:*grep-max-line-length*
   #:*search-ignored-directory-names*
   #:*diff-display-max-lines*
   #:*lisp-eval-default-package*
   #:*last-eval-result*
   #:*last-eval-condition*
   #:*lisp-eval-history*
   #:*lisp-eval-history-limit*
   #:*lisp-eval-max-output-chars*
   #:lisp-eval-record
   #:lisp-eval-record-code
   #:lisp-eval-record-package
   #:lisp-eval-record-result
   #:lisp-eval-record-output
   #:lisp-eval-record-error-output
   #:lisp-eval-record-condition
   #:lisp-eval-record-timestamp
   #:lisp-data-string
   #:lisp-data-read
   #:tool-error-result-data
   #:tool-key-name
   #:tool-key=
   #:tool-plist-p
   #:tool-args-alist
   #:tool-arg
   #:compute-simple-diff
   #:tool-working-directory-pathname
   #:resolve-tool-path
   #:execute-read
   #:execute-find
   #:execute-grep
   #:execute-write
   #:execute-edit
   #:execute-lisp-eval
   #:eval-history-to-string)
  (:export
   ;; General utilities
   #:count-occurrences

   ;; Lines
   #:line
   #:make-line
   #:line-content
   #:line-next
   #:line-prev

   ;; Messages
   #:message
   #:make-message
   #:message-first-line
   #:message-last-line
   #:message-point-line
   #:message-point-offset
   #:message-mark-line
   #:message-mark-offset
   #:message-sender
   #:message-timestamp
   #:message-read-only-p
   #:message-next
   #:message-prev
   #:message-raw-content
   #:message-metadata
   #:message-entry-id
   #:message-parent-entry-id
   #:message-text
   #:message-line-count

   ;; Sessions
   #:*sessions-dir*
   #:session
   #:session-name
   #:session-display-name
   #:session-id
   #:session-directory
   #:session-manifest-path
   #:session-transcript-directory
   #:session-current-transcript-index
   #:session-current-transcript-path
   #:session-current-leaf-id
   #:session-parent-session
   #:session-working-directory
   #:session-tree-node
   #:session-tree-node-entry
   #:session-tree-node-label
   #:session-tree-node-children
   #:session-normalized-tree-events
   #:session-tree-roots
   #:session-active-path-ids
   #:session-active-branch-message-events
   #:session-branch-state
   #:session-effective-leaf-id
   #:session-find-entry
   #:session-navigation-leaf-for-entry
   #:session-entry-user-message-text
   #:session-display-name-or-name
   #:set-session-display-name
   #:set-session-current-leaf
   #:record-session-compaction
   #:record-session-branch-summary
   #:record-session-label-change
   #:record-session-model-change
   #:record-session-think-level-change
   #:create-branched-session
   #:load-or-create-session
   #:record-session-message
   #:rotate-session-transcript
   #:export-buffer-session-html
   #:share-session-export
   #:session-share-handler
   #:session-share-handler-name
   #:session-share-handler-description
   #:session-share-handler-function
   #:register-session-share-handler
   #:find-session-share-handler
   #:list-session-share-handlers

   ;; Message editing
   #:message-insert-char
   #:message-insert-newline
   #:set-message-text
   #:message-delete-char-backward
   #:message-delete-char-forward
   #:message-forward-char
   #:message-backward-char
   #:message-forward-word
   #:message-backward-word
   #:message-forward-line
   #:message-backward-line
   #:message-beginning-of-buffer
   #:message-end-of-buffer
   #:message-point-absolute-offset
   #:set-message-point-from-absolute-offset
   #:message-mark-active-p
   #:message-mark-absolute-offset
   #:set-message-mark-from-absolute-offset
   #:message-set-mark-at-point
   #:message-clear-mark
   #:message-region-bounds
   #:message-region-text
   #:message-delete-region
   #:message-kill-region
   #:message-copy-region
   #:message-exchange-point-and-mark
   #:message-mark-whole-buffer
   #:message-current-line-number
   #:message-current-column-number
   #:message-search-forward
   #:message-search-backward
   #:message-move-beginning-of-line
   #:message-move-end-of-line
   #:message-kill-line
   #:message-kill-backward-line
   #:message-kill-word
   #:message-backward-kill-word
   #:message-yank
   #:message-yank-pop

   ;; Kill ring
   #:*kill-ring*
   #:kill-ring-push
   #:kill-ring-top

   ;; Buffer
   #:*default-context-limit*
   #:*default-agent-name*
   #:*default-show-tool-results*
   #:*default-collapse-tool-activity*
   #:*default-show-reasoning-output*
   #:*default-show-metadata-output*
   #:*default-pipeline-name*
   #:*default-buffer-session-persistence-mode*
   #:*scratch-buffer-name*
   #:*scratch-buffer-initial-text*
   #:*listener-buffer-name*
   #:buffer
   #:make-buffer
   #:buffer-type
   #:make-buffer-type
   #:buffer-type-name
   #:buffer-type-description
   #:buffer-type-major-mode
   #:buffer-type-document-p
   #:buffer-type-presentation-function
   #:buffer-type-input-presentation-function
   #:buffer-type-serialize-state-function
   #:buffer-type-restore-state-function
   #:buffer-type-package
   #:register-buffer-type
   #:define-buffer-type
   #:find-buffer-type
   #:list-buffer-types
   #:buffer-type-for-buffer
   #:buffer-presentation-function
   #:buffer-input-presentation-function
   #:register-buffer-input-presentation-provider
   #:remove-buffer-input-presentation-providers-for-package
   #:buffer-input-presentation-functions
   #:buffer-name
   #:buffer-first-message
   #:buffer-last-message
   #:buffer-input-message
   #:buffer-agent-name
   #:buffer-kind
   #:buffer-working-directory
   #:buffer-project-name
   #:buffer-resource-path
   #:buffer-original-text
   #:buffer-dirty-p
   #:buffer-token-count
   #:buffer-context-limit
   #:buffer-status
   #:buffer-provider-override
   #:buffer-model-override
   #:buffer-think-level-override
   #:buffer-model-role-override
   #:buffer-model-role-set-override
   #:buffer-service-tier-override
   #:buffer-pipeline-name
   #:buffer-enabled-packages
   #:buffer-session
   #:buffer-session-persistence-mode
   #:buffer-persistent-session-p
   #:buffer-ephemeral-p
   #:set-buffer-provider-override
   #:set-buffer-model-override
   #:set-buffer-think-level-override
   #:set-buffer-model-role-override
   #:set-buffer-model-role-set-override
   #:set-buffer-service-tier-override
   #:clear-buffer-provider-override
   #:clear-buffer-model-override
   #:clear-buffer-think-level-override
   #:clear-buffer-model-role-override
   #:clear-buffer-model-role-set-override
   #:clear-buffer-service-tier-override
   #:clear-buffer-routing-overrides
   #:set-buffer-pipeline
   #:clear-buffer-pipeline
   #:buffer-keymap
   #:buffer-scroll-offset
   #:buffer-show-tool-results-p
   #:buffer-collapse-tool-activity-p
   #:buffer-show-reasoning-p
   #:buffer-show-metadata-p
   #:buffer-pending-stream
   #:buffer-streaming-message
   #:*buffer-ring*
   #:current-buffer
   #:add-buffer-to-ring
   #:switch-to-buffer
   #:kill-buffer-from-ring
   #:find-buffer-by-name
   #:scratch-buffer-p
   #:file-buffer-p
   #:info-buffer-p
   #:listener-buffer-p
   #:document-buffer-p
   #:buffer-llm-running-p
   #:make-chat-buffer
   #:make-info-buffer
   #:scratch-buffer
   #:ensure-scratch-buffer
   #:scratch-buffer-text
   #:file-buffer-text
   #:info-buffer-text
   #:ensure-file-keymap-initialized
   #:file-buffer-dirty-p
   #:mark-buffer-dirty
   #:next-buffer-name
   #:buffer-names
   #:buffer-finalize-input

   ;; Listener buffers
   #:classify-listener-line
   #:next-listener-input-mode
   #:listener-prompt-string
   #:expand-prose-interpolations
   #:prose-interpolation-error
   #:prose-interpolation-error-substring
   #:prose-interpolation-error-cause
    #:listener-context
    #:make-listener-context
    #:listener-context-package-name
    #:listener-context-directory-stack
    #:listener-context-input-mode
    #:listener-context-push-directory
    #:listener-context-pop-directory
    #:listener-context-set-package
    #:listener-context-set-input-mode
    #:unknown-listener-package
    #:unknown-listener-package-name
    #:empty-listener-directory-stack
    #:run-listener-shell-command
    ;; Listener frame fixture and delegated presentation acceptance
    #:*listener-input-mode*
    #:rplaca-listener
    #:rplaca-listener-context
    #:define-rplaca-listener-command
    #:listener-input-token
    #:make-listener-input-token
    #:listener-input-token-kind
    #:listener-input-token-value
    #:listener-input-token-source
    #:rplaca-package
    #:prose
    #:command-form-or-prose
    ;; Listener frame, details surface, lifecycle
    #:rplaca-listener-conversation-buffer
    #:rplaca-listener-pending-session-name
    #:rplaca-listener-session-label
    #:rplaca-listener-appearance-profile
    #:rplaca-listener-pending-assistant-turn
    #:rplaca-listener-selected-detail
    #:rplaca-listener-liveness
    #:rplaca-listener-progress
    #:set-rplaca-listener-selected-detail
    #:clear-rplaca-listener-selected-detail
    #:assistant-turn
    #:make-assistant-turn
    #:assistant-turn-primary-text
    #:assistant-turn-tool-uses
    #:assistant-turn-reasoning
    #:assistant-turn-metadata
    #:assistant-turn-artifact-refs
    #:assistant-turn-media-refs
    #:assistant-turn-inspect-payload
    #:assistant-turn-status
    #:turn-facet
    #:make-turn-facet
    #:turn-facet-turn
    #:turn-facet-kind
    #:display-turn-details
    #:display-listener-wholine
    #:listener-print-prompt
    #:listener-frame-top-level
    #:listener-frame-cleanup
    #:rplaca-listener-pane-appearance-snapshot
    #:listener-resolve-pane-appearance-initargs
    #:listener-pane-appearance-initargs
    #:make-rplaca-listener-pane
    #:run-rplaca-listener
   #:listener-state
   #:make-listener-state
   #:listener-state-package-name
   #:listener-state-directory-stack
   #:listener-state-last-values
   #:listener-state-command-history
   #:listener-buffer-state
   #:listener-prompt-text
   #:listener-wholine-text
   #:listener-command-help-text
   #:make-listener-buffer
   #:ensure-listener-buffer
   #:submit-listener-input
   ;; Font editor buffers
   #:*font-editor-buffer-name*
   #:*font-editor-default-extract-directory*
   #:bitmap-glyph
   #:make-bitmap-glyph
   #:bitmap-glyph-code
   #:bitmap-glyph-name
   #:bitmap-glyph-advance-width
   #:bitmap-glyph-x-offset
   #:bitmap-glyph-y-offset
   #:bitmap-glyph-bitmap
   #:bitmap-font
   #:make-empty-bitmap-font
   #:bitmap-font-name
   #:bitmap-font-line-spacing
   #:bitmap-font-baseline
   #:bitmap-font-default-width
   #:bitmap-font-blinker-width
   #:bitmap-font-blinker-height
   #:bitmap-font-glyph
   #:bitmap-font-glyph-codes
   #:font-editor-state
   #:font-editor-buffer-p
   #:font-editor-buffer-state
   #:font-editor-current-font
   #:font-editor-current-glyph
   #:make-font-editor-buffer
   #:ensure-font-editor-buffer
   #:read-font-file
   #:write-rplacafont-file
   #:read-rplacafont-file
   #:write-bdf-font
   #:import-bdf-font
   #:import-ast-font
   #:extract-genera-bdf-fonts
   #:font-editor-command
   #:font-editor-open-file-command
   #:font-editor-save-font-command
   #:font-editor-export-bdf-command
   #:font-editor-set-sample-string-command
   #:font-editor-extract-genera-fonts-command

   ;; Appearance declarations and resolution
   #:appearance-unspecified-p
   #:appearance-logical-sizes
   #:appearance-relative-sizes
   #:appearance-role-kinds
   #:appearance-condition
   #:appearance-error
   #:appearance-condition-origin
   #:appearance-condition-role
   #:appearance-condition-axis
   #:appearance-condition-value
   #:appearance-condition-path
   #:appearance-condition-port
   #:appearance-condition-available-choices
   #:appearance-condition-fatal-p
   #:appearance-condition-suggested-repairs
   #:make-appearance-condition
   #:signal-appearance-condition
   #:error-appearance-condition
   #:warn-appearance-condition
   #:unknown-appearance-role
   #:invalid-appearance-component
   #:appearance-theme-cycle
   #:appearance-role-cycle
   #:missing-appearance-parent
   #:invalid-appearance-fallback
   #:unsupported-role-axis
   #:ambiguous-font-family
   #:ambiguous-font-face
   #:font-unavailable
   #:font-size-unavailable
   #:missing-font-family
   #:missing-font-face
   #:invalid-scalable-font-size
   #:invalid-fixed-font-size
   #:font-mapping-invalid
   #:font-metrics-invalid
   #:font-metric-medium-unavailable
   #:fixed-width-font-required
   #:relative-size-base-invalid
   #:device-font-port-mismatch
   #:appearance-contrast-warning
   #:appearance-live-update-unsupported
   #:appearance-activation-failed
   #:appearance-typography-spec
   #:make-appearance-typography-spec
   #:appearance-typography-spec-family
   #:appearance-typography-spec-face
   #:appearance-typography-spec-size
   #:portable-font-descriptor
   #:make-portable-font-descriptor
   #:portable-font-descriptor-family
   #:portable-font-descriptor-face
   #:portable-font-descriptor-size
   #:enumerated-font-choice
   #:make-enumerated-font-choice
   #:enumerated-font-choice-family-display
   #:enumerated-font-choice-face-display
   #:enumerated-font-choice-size
   #:font-choice-kind
   #:appearance-font-inventory
   #:appearance-font-inventory-generation
   #:appearance-font-inventory-choices
   #:enumerate-port-font-inventory
   #:resolve-enumerated-font-choice
   #:appearance-ink-spec
   #:make-appearance-ink-spec
   #:appearance-ink-spec-foreground
   #:appearance-surface-spec
   #:make-appearance-surface-spec
   #:appearance-surface-spec-background
   #:appearance-decoration-spec
   #:make-appearance-decoration-spec
   #:appearance-decoration-spec-kind
   #:appearance-decoration-spec-parameters
   #:appearance-role-style
   #:make-appearance-role-style
   #:appearance-role-style-typography
   #:appearance-role-style-foreground-ink
   #:appearance-role-style-surface
   #:appearance-role-style-decoration
   #:appearance-role-definition
   #:make-appearance-role-definition
   #:appearance-role-definition-id
   #:appearance-role-definition-kind
   #:appearance-role-definition-documentation
   #:appearance-role-definition-fallback-role
   #:appearance-role-definition-supported-axes
   #:appearance-role-definition-owner
   #:appearance-role-supported-axes
   #:appearance-role-supports-axis-p
   #:validate-appearance-role-style
   #:appearance-theme-definition
   #:make-appearance-theme-definition
   #:appearance-theme-definition-id
   #:appearance-theme-definition-documentation
   #:appearance-theme-definition-parent-theme
   #:appearance-theme-definition-role-overlays
   #:appearance-theme-definition-owner
   #:appearance-profile
   #:make-appearance-profile
   #:appearance-profile-selected-theme
   #:appearance-profile-strict-contrast
   #:appearance-profile-role-overrides
   #:appearance-config-pathname
   #:read-appearance-profile-file
   #:write-appearance-profile-file
   #:serialize-appearance-profile
   #:parse-appearance-theme-selector
   #:parse-appearance-startup-arguments
   #:resolve-startup-appearance-profile
   #:reload-appearance-file-profile
   #:save-staged-appearance-profile
   #:*appearance-startup-resolution-count*
   #:*appearance-configuration-access-count*
   #:appearance-catalog
   #:make-appearance-catalog
   #:appearance-catalog-role-definitions
   #:appearance-catalog-theme-definitions
   #:appearance-catalog-built-in-overlays
   #:appearance-catalog-generation
   #:find-appearance-role-definition
   #:find-appearance-theme-definition
   #:appearance-role-fallback-chain
   #:appearance-theme-parent-chain
   #:appearance-logical-size-index
   #:resolve-appearance-relative-size
   #:merge-appearance-typography
   #:merge-appearance-role-style
   #:appearance-role-style-key
   #:resolved-appearance-role
   #:resolved-appearance-role-style
   #:resolved-appearance-role-provenance
   #:resolved-appearance-role-structural-key
   #:resolved-appearance-role-diagnostics
   #:appearance-diagnostic
   #:appearance-diagnostic-catalog-generation
   #:appearance-diagnostic-unknown-role
   #:appearance-diagnostic-condition
   #:appearance-diagnostic-deduplication-key
   #:resolve-appearance-role
   #:resolve-appearance-role-stack
   #:resolve-runtime-appearance-role-stack
   #:make-classic-appearance-catalog
   #:resolved-appearance-bundle
   #:resolved-appearance-bundle-catalog-generation
   #:resolved-appearance-bundle-profile
   #:resolved-appearance-bundle-profile-revision
   #:resolved-appearance-bundle-font-inventory-generation
   #:resolved-appearance-bundle-port-identity
   #:resolved-appearance-bundle-role-table
   #:resolved-appearance-bundle-surface-defaults
   #:resolved-appearance-bundle-role-keys
   #:resolved-appearance-bundle-provenance
   #:resolved-appearance-bundle-bundle-key
   #:resolve-appearance-profile-bundle
   #:appearance-candidate
   #:make-appearance-candidate
   #:appearance-candidate-profile
   #:appearance-activation-classification
   #:appearance-activation-classification-status
   #:appearance-activation-classification-deltas
   #:appearance-activation-result
   #:appearance-activation-result-status
   #:appearance-activation-result-candidate
   #:appearance-activation-result-classification
   #:appearance-activation-result-diagnostics
   #:appearance-activation-result-bundle
   #:buffer-clear-history-before-input
   #:buffer-insert-read-only-message
   #:buffer-insert-agent-message
   #:buffer-insert-system-message
   #:buffer-insert-context-message
   #:notify-buffer-display-change
   #:buffer-message-count
   #:save-session
   #:replace-buffer-history-with-serialized-messages
   #:load-session
   #:list-saved-sessions

   ;; Windows
   #:rplaca-window
   #:make-rplaca-window
   #:rplaca-window-id
   #:rplaca-window-buffer
   #:rplaca-window-node
   #:rplaca-window-node-kind
   #:rplaca-window-node-window
   #:rplaca-window-node-orientation
   #:rplaca-window-node-first
   #:rplaca-window-node-second
   #:make-rplaca-window-tree
   #:make-rplaca-window-leaf
   #:make-rplaca-window-split
   #:rplaca-window-node-leaf-p
   #:rplaca-window-node-split-p
   #:rplaca-window-tree-windows
   #:rplaca-window-tree-count
   #:rplaca-window-tree-find-window
   #:rplaca-window-tree-find-node
   #:split-rplaca-window-tree
   #:rplaca-window-tree-next-window
   #:delete-rplaca-window-from-tree
   #:delete-other-rplaca-windows
   #:rplaca-window-tree-replace-dead-buffers
   #:rplaca-window-layout-entry
   #:rplaca-window-layout-entry-window
   #:rplaca-window-layout-entry-row
   #:rplaca-window-layout-entry-col
   #:rplaca-window-layout-entry-rows
   #:rplaca-window-layout-entry-cols
   #:rplaca-window-separator
   #:rplaca-window-separator-orientation
   #:rplaca-window-separator-row
   #:rplaca-window-separator-col
   #:rplaca-window-separator-rows
   #:rplaca-window-separator-cols
   #:rplaca-window-tree-layout

   ;; Commands
   #:*current-caller*
   #:*tool-working-directory*
   #:*command-table*
   #:command-metadata
   #:command-metadata-name
   #:command-metadata-docstring
   #:command-metadata-keybindings
   #:command-metadata-lambda-list
   #:command-metadata-prompts
   #:command-metadata-package
   #:defcommand
   #:list-available-commands
   #:command-required-arguments
   #:resolve-command-prompt-reader

   ;; Extended documentation
   #:*extended-docs*
   #:defdoc
   #:extended-doc
   #:deftool
   #:agent-tool-metadata
   #:agent-tool-metadata-symbol
   #:agent-tool-metadata-name
   #:agent-tool-metadata-description
   #:agent-tool-metadata-args
   #:agent-tool-metadata-input-schema
   #:agent-tool-metadata-call-style
   #:agent-tool-metadata-execution
   #:agent-tool-metadata-command-p
   #:agent-tool-metadata-lambda-list
   #:agent-tool-metadata-package
   #:register-agent-tool-metadata
   #:unregister-agent-tool-metadata
   #:find-agent-tool-metadata
   #:list-agent-tool-metadata
   #:undocumented-functions
   #:undocumented-variables

   ;; Keymaps
   #:keymap
   #:make-keymap
   #:keymap-name
   #:keymap-bindings
   #:keymap-parent
   #:keymap-bind
   #:keymap-lookup
   #:*default-keymap*
   #:*file-keymap*
   #:*alt-emulates-meta*

   ;; Projects
   #:project
   #:make-project
   #:project-name
   #:project-root
   #:project-description
   #:project-source
   #:project-systems
   #:project-packages
   #:project-check-functions
   #:project-reload-function
   #:change-set
   #:make-change-set
   #:change-set-id
   #:change-set-name
   #:change-set-description
   #:change-set-entries
   #:change-set-status
   #:change-set-created-at
   #:change-set-applied-at
   #:change-set-entry
   #:change-set-entry-kind
   #:change-set-entry-project-name
   #:change-set-entry-path
   #:change-set-entry-new-path
   #:change-set-entry-new-text
   #:change-set-entry-old-exists-p
   #:change-set-entry-old-text
   #:change-set-entry-target-old-exists-p
   #:change-set-entry-target-old-text
   #:change-set-entry-applied-p
   #:*project-definitions-directory*
   #:*project-registry*
   #:*project-manifest-extension*
   #:*project-ignored-directory-names*
   #:*project-list-file-limit*
   #:*project-search-result-limit*
   #:*change-set-registry*
   #:*current-change-set*
   #:define-project
   #:create-project
   #:register-project
   #:find-project
   #:list-projects
   #:load-project-definitions
   #:reload-projects
   #:project-resolve-path
   #:project-list-files
   #:project-read-file
   #:project-create-file
   #:project-save-file
   #:project-search
   #:project-search-to-string
   #:project-open-file
   #:find-project-file-buffer
   #:project-save-buffer
   #:begin-change-set
   #:current-change-set
   #:find-change-set
   #:list-change-sets
   #:stage-project-file
   #:stage-project-delete
   #:stage-project-rename
   #:change-set-project-file-text
   #:change-set-diff-to-string
   #:change-set-summary-to-string
   #:apply-change-set
   #:discard-change-set
   #:revert-change-set
   #:run-project-checks
   #:compile-project-file
   #:load-project-file
   #:reload-project-system
   #:project-outline-to-string
   #:project-find-definitions
   #:project-find-definitions-to-string
   #:project-find-references-to-string
   #:project-package-map-to-string
   #:project-describe-definition-to-string
   #:load-project-declared-packages

   ;; Skills
   #:skill
   #:make-skill
   #:skill-name
   #:skill-description
   #:skill-short-description
   #:skill-display-name
   #:skill-interface-short-description
   #:skill-default-prompt
   #:skill-icon-small
   #:skill-icon-large
   #:skill-brand-color
   #:skill-allow-implicit-invocation-p
   #:skill-path
   #:skill-root
   #:skill-scope
   #:skill-source
   #:skill-contents
   #:skill-root-definition
   #:make-skill-root
   #:skill-root-path
   #:skill-root-scope
   #:skill-root-source
   #:skill-error
   #:make-skill-error
   #:skill-error-path
   #:skill-error-message
   #:skill-load-outcome
   #:skill-load-outcome-skills
   #:skill-load-outcome-errors
   #:skill-load-outcome-disabled-paths
   #:*skill-user-directory*
   #:*skill-agents-directory*
   #:*skill-system-directory*
   #:*skill-configuration-path*
   #:*skill-roots*
   #:*programmatic-skills*
   #:*skill-scan-max-depth*
   #:*skill-scan-max-directories-per-root*
   #:*skill-list-file-limit*
   #:*skill-search-result-limit*
   #:register-skill-root
   #:register-skill-definition
   #:reload-skills
   #:clear-skills-cache
   #:ensure-skills-loaded
   #:list-skills
   #:list-skill-errors
   #:list-skills-to-string
   #:find-skill
   #:skill-enabled-p
   #:set-skill-enabled
   #:enable-skill
   #:disable-skill
   #:save-skill-configuration
   #:read-skill-instructions
   #:skill-list-files
   #:skill-read-file
   #:skill-search-to-string
   #:describe-skill-to-string
   #:collect-skill-mentions
   #:skill-injection-messages
   #:render-skills-section

   ;; Prompt templates and slash commands
   #:prompt-template
   #:make-prompt-template
   #:prompt-template-name
   #:prompt-template-description
   #:prompt-template-body
   #:prompt-template-path
   #:prompt-template-scope
   #:prompt-template-package
   #:slash-command
   #:make-slash-command
   #:slash-command-name
   #:slash-command-description
   #:slash-command-argument-hint
   #:slash-command-handler
   #:slash-command-package
   #:*slash-command-table*
   #:register-slash-command
   #:list-slash-commands
   #:find-slash-command
   #:parse-slash-command-line
   #:parse-prompt-template-markdown
   #:discover-prompt-templates-in-directory
   #:discover-prompt-templates
   #:expand-prompt-template-body
   #:process-slash-command

    ;; LLM
    #:*zai-env-var*
    #:read-env-token
    #:provider-token-path
    #:read-provider-token
    #:save-provider-token
     #:agent-definition
     #:make-agent-definition
     #:agent-definition-name
     #:agent-definition-provider
     #:agent-definition-model
     #:agent-definition-think-level
     #:agent-definition-core-prompt
     #:agent-definition-personality-prompt
     #:agent-definition-tool-names
     #:agent-definition-package
     #:register-agent-definition
     #:find-agent-definition
     #:list-agent-definitions
     #:package-owned-agent-definitions
     #:remove-agent-definitions-for-package
     #:load-agent-defaults
     #:save-agent-defaults
     #:agent-default
     #:set-agent-default
     #:ensure-agent-defaults-loaded
     #:resolve-buffer-provider-and-model
     #:build-agent-system-prompt
     #:*default-core-system-prompt*
     #:*default-personality-prompt*
     #:*personality-prompt-path*
     #:load-personality-prompt-file
     #:provider-model-supported-think-levels
     #:reconcile-buffer-think-level-override
     #:resolve-buffer-service-tier
     #:artifactum-session-records
     #:artifactum-find-record
     #:artifactum-create-from-file
     #:artifactum-create-from-content
     #:artifactum-create-from-octets
     #:artifactum-update-record
     #:artifactum-read-record-data
     #:artifactum-reference-text
     #:artifactum-buffer-state-serializer
     #:artifactum-buffer-state-restorer
     #:artifactum-artifact-buffer-open-record
     ;; Provider-neutral generated media
     #:media-provider
     #:make-media-provider
     #:media-provider-id
     #:media-provider-kinds
     #:media-provider-start-fn
     #:media-provider-poll-fn
     #:media-provider-cancel-fn
     #:media-provider-package
     #:media-request
     #:media-request-id
     #:media-request-kind
     #:media-request-prompt
     #:media-request-referenced-image-paths
     #:media-asset
     #:make-media-asset
     #:media-asset-name
     #:media-asset-mime-type
     #:media-asset-octets
     #:media-asset-metadata
     #:media-provider-outcome
     #:make-media-provider-outcome
     #:media-provider-outcome-status
     #:media-provider-outcome-assets
     #:media-provider-outcome-revised-prompt
     #:media-provider-outcome-backend-id
     #:media-provider-outcome-public-error
     #:media-operation
     #:media-operation-id
     #:media-operation-provider-id
     #:media-operation-request
     #:media-operation-status
     #:media-operation-backend-id
     #:media-operation-outcome
     #:media-operation-error
     #:media-operation-artifact-records
     #:register-media-provider
     #:find-media-provider
     #:list-media-providers
     #:remove-media-providers-for-package
     #:media-default-provider
     #:set-media-default-provider
     #:make-media-generation-request
     #:start-media-operation
     #:find-media-operation
     #:poll-media-operation
     #:cancel-media-operation
     #:persist-media-operation-assets
     #:media-operation-data
     #:*boot-file-names*
     #:load-boot-files
     #:*agent-defaults-path*
     #:build-conversation-messages
   #:*default-provider*
   #:*default-model*
   #:*default-max-tokens*
   #:*openai-codex-reasoning-summary*
   #:api-json-encode
   #:api-json-decode

   ;; Compaction
   #:*compaction-point*
   #:*compaction-function*
   #:*compaction-prompt*
   #:*compaction-summary-prefix*
   #:*compaction-preserved-user-message-token-limit*
   #:buffer-conversation-token-estimate
   #:compaction-threshold-tokens
   #:compaction-needed-p
   #:maybe-compact-buffer
   #:default-compact-buffer
   #:compact-buffer-command

   ;; Z.AI (Zhipu AI)
   #:*zai-model*
   #:*zai-api-url*
   #:zai-request
   #:zai-request-streaming

   ;; OpenRouter
   #:*openrouter-model*
   #:*openrouter-api-url*
   #:*openrouter-models-url*
   #:*openrouter-env-var*
   #:*openrouter-cached-models*
   #:fetch-openrouter-models
   #:openrouter-request
   #:openrouter-request-streaming

   ;; OpenAI Codex OAuth
   #:*openai-oauth-client-id*
   #:*openai-oauth-auth-url*
   #:*openai-oauth-token-url*
   #:*openai-oauth-redirect-uri*
   #:*openai-oauth-scopes*
   #:*codex-auth-path*
   #:generate-code-verifier
   #:compute-code-challenge
   #:generate-oauth-state
   #:url-encode-param
   #:extract-oauth-callback-params
   #:openai-codex-oauth-start
   #:exchange-openai-oauth-code
   #:save-openai-codex-oauth-tokens
   #:read-openai-codex-oauth-tokens
   #:refresh-openai-codex-oauth-token
   #:read-openai-codex-oauth-token
   #:openai-codex-oauth-finish
   #:*openai-oauth-pending*
   #:openai-codex-oauth-command

   ;; Tools
   #:*http-fetch-max-chars*
   #:*http-connection-timeout*
   #:*http-user-agent*
   #:*file-read-default-limit*
   #:*find-default-limit*
   #:*grep-default-limit*
   #:*grep-max-file-bytes*
   #:*grep-max-line-length*
   #:*search-ignored-directory-names*
   #:*shell-exec-default-timeout*
   #:*diff-display-max-lines*
   #:*lisp-eval-default-package*
   #:*last-eval-result*
   #:*last-eval-condition*
   #:*lisp-eval-history*
   #:*lisp-eval-history-limit*
   #:*lisp-eval-max-output-chars*
   #:tool-working-directory-pathname
   #:resolve-tool-path
   #:*tool-table*
   #:*active-tool-names*
   #:*temporary-tool-table*
   #:*current-tool-buffer*
   #:lisp-eval-record
   #:lisp-eval-record-code
   #:lisp-eval-record-package
   #:lisp-eval-record-result
   #:lisp-eval-record-output
   #:lisp-eval-record-error-output
   #:lisp-eval-record-condition
   #:lisp-eval-record-timestamp
   #:tool-definition
   #:tool-definition-name
   #:tool-definition-description
   #:tool-definition-input-schema
   #:tool-definition-execution
   #:tool-definition-execute-fn
   #:tool-definition-package
   #:subagent-tool
   #:subagent-tool-name
   #:subagent-tool-description
   #:subagent-tool-input-schema
   #:subagent-tool-execution
   #:subagent-tool-execute-fn
   #:make-subagent-tool
   #:register-tool
   #:execute-tool
   #:tool-definitions-for-api
   #:render-agent-tools-section
   #:format-tool-call-sexpr
   #:format-tool-call-expanded
   #:eval-history-to-string
   #:init-tools

   ;; Safe in-place reload
   #:rplaca-safe-reload
   #:rplaca-safe-reload-preflight
   #:rplaca-reload-result-ok-p
   #:rplaca-reload-result-summary
   #:call-with-runtime-admission
   #:call-with-runtime-settlement-admission
   #:runtime-admission-closed
   #:safe-reload-rplaca-command

   ;; Standard reference / library discovery
   #:*common-lisp-spec-root*
   #:common-lisp-spec-available-p
   #:find-common-lisp-spec-entry
   #:describe-common-lisp-symbol-to-string
   #:search-common-lisp-spec-to-string
   #:list-project-systems
   #:describe-system-to-string
   #:list-system-packages
   #:list-package-functions
   #:list-package-variables
   #:list-package-types
   #:describe-library-symbol-to-string
   #:search-system-docs

   ;; Sexed structural editing
   #:sexed-balanced-p
   #:balanced-parentheses-p
   #:sexed-diagnostics
   #:sexed-find-forms
   #:sexed-form-text
   #:sexed-outline-to-string
   #:sexed-replace-form
   #:sexed-delete-form
   #:sexed-insert-before-form
   #:sexed-insert-after-form
   #:sexed-insert-form-before
   #:sexed-insert-form-after
   #:sexed-wrap-form
   #:sexed-splice-form
   #:sexed-raise-form
   #:sexed-slurp-forward
   #:sexed-barf-forward
   #:sexed-read-file-text
   #:sexed-write-file-text
   #:sexed-file-outline-to-string
   #:sexed-file-form-text
   #:sexed-replace-file-form
   #:sexed-delete-file-form
   #:sexed-insert-before-file-form
   #:sexed-insert-after-file-form
   #:sexed-insert-file-form-before
   #:sexed-insert-file-form-after
   #:sexed-wrap-file-form
   #:sexed-splice-file-form
   #:sexed-raise-file-form
   #:sexed-slurp-forward-file-form
   #:sexed-barf-forward-file-form
   #:sexed-write-project-file-text
   #:sexed-project-outline-to-string
   #:sexed-project-form-text
   #:sexed-replace-project-form
   #:sexed-delete-project-form
   #:sexed-insert-before-project-form
   #:sexed-insert-after-project-form
   #:sexed-insert-project-form-before
   #:sexed-insert-project-form-after
   #:sexed-wrap-project-form
   #:sexed-splice-project-form
   #:sexed-raise-project-form
   #:sexed-slurp-forward-project-form
   #:sexed-barf-forward-project-form

   ;; Slop symbol intelligence
   #:*slop-default-result-limit*
   #:*slop-project-index-cache*
   #:slop-list-projects
   #:slop-current-project
   #:slop-index-project
   #:slop-project-symbols
   #:slop-symbol-at
   #:slop-find-definitions
   #:slop-find-definitions-batch
   #:slop-find-references
   #:slop-find-callers
   #:slop-find-callees
   #:slop-trace-calls
   #:slop-find-mentions
   #:slop-definition-context
   #:slop-find-variable-uses
   #:slop-rename-variable

   ;; Tool sequencing
   #:buffer-stashed-input
   #:buffer-pending-tool-calls
   #:buffer-tool-call-results
   #:buffer-pending-tool-execution
   #:buffer-pending-interactive-operation
   #:buffer-runtime-generation
   #:buffer-disposed-p
   #:dispose-buffer

   ;; Buffer selector
   #:*buffer-selector-active*
   #:*buffer-selector-index*
   #:*session-tree-selector-active*
   #:*session-tree-selector-buffer*
   #:*session-tree-selector-items*
   #:*session-tree-selector-filtered-items*
   #:*session-tree-selector-index*
   #:*session-tree-selector-scroll*
   #:*session-tree-selector-search*
   #:*session-tree-selector-filter-mode*
   #:*session-tree-selector-folded-ids*
   #:session-tree-selector-activate
   #:session-tree-selector-deactivate
   #:session-tree-selector-update-filter
   #:session-tree-selector-current-item
   #:handle-session-tree-selector-key
   #:session-tree-command
   #:fork-session-command
   #:list-buffers-command
   #:minibuffer-select-project-command
   #:open-project-file-command
   #:create-project-file-command
   #:search-project-command
   #:insert-tab-command
   #:next-line-command
   #:previous-line-command
   #:beginning-of-buffer-command
   #:end-of-buffer-command
   #:set-mark-command
   #:keyboard-quit-command
   #:kill-region-command
   #:copy-region-command
   #:exchange-point-and-mark-command
   #:mark-whole-buffer-command
   #:search-forward-command
   #:search-backward-command
   #:revert-file-buffer-command
   #:write-project-file-as-command
   #:insert-file-command
   #:minibuffer-insert-skill-command
   #:minibuffer-toggle-skill-command
   #:list-skills-command
   #:minibuffer-toggle-package-command
   #:describe-installed-package-command
   #:package-dashboard-command
   #:switch-appearance-theme-command
   #:describe-current-appearance-command
   #:customize-appearance-command
   #:customize-face-command
   #:apply-staged-appearance-command
   #:save-appearance-command
   #:revert-staged-appearance-command
   #:reload-appearance-file-command
   #:refresh-font-inventory-command

   ;; Model selector (overlay)
   #:*model-selector-active*
   #:*model-selector-index*
   #:*model-selector-entries*
   #:select-model-command
   #:handle-model-selector-key
   #:*think-selector-active*
   #:*think-selector-index*
   #:*think-selector-entries*
   #:select-think-level-command
   #:handle-think-selector-key

   ;; Minibuffer
   #:*minibuffer-active*
   #:*minibuffer-mode*
   #:*minibuffer-prompt*
   #:*minibuffer-input*
   #:*minibuffer-point*
   #:*minibuffer-items*
   #:*minibuffer-filtered-items*
   #:*minibuffer-selected-index*
   #:*minibuffer-scroll-offset*
   #:*minibuffer-match-positions*
   #:*minibuffer-callback*
   #:*minibuffer-max-height*
   #:*automatic-skill-completion-enabled*
   #:*skill-completion-enabled-buffer-kinds*
   #:*skill-completion-max-height*
   #:*model-selection-history*
   #:matching-core-available-p
   #:split-query-tokens
   #:fuzzy-token-match-p
   #:fuzzy-token-positions
   #:fuzzy-match-positions
   #:fuzzy-token-score
   #:fuzzy-score
   #:fuzzy-match-p
   #:minibuffer-item-display
   #:minibuffer-item-match-text
   #:minibuffer-activate
   #:minibuffer-prompt
   #:minibuffer-deactivate
   #:minibuffer-update-filter
   #:minibuffer-visible-item-count
   #:minibuffer-ensure-visible
   #:minibuffer-confirm
   #:minibuffer-cancel
   #:handle-minibuffer-key
   #:sort-models-by-recency
   #:*buffer-selection-history*
   #:sort-buffers-by-recency
   #:invoke-command
   #:execute-extended-command
   #:minibuffer-select-agent-command
   #:minibuffer-select-model-command
   #:minibuffer-select-think-level-command
   #:minibuffer-select-buffer-command
   #:load-session-command
   #:continue-session-command
   #:session-info-command
   #:set-session-display-name-command
   #:new-listener-buffer-command
   #:info-directory-command
   #:info-open-manual-command
   #:rplaca-manual-command
   #:info-goto-node-command
   #:help-buffer-p
   #:help-buffer-text

   ;; Introspection / Help
   #:list-functions
   #:find-keybindings-for-command
   #:format-key-binding
   #:describe-function-to-string
   #:make-help-buffer
   #:describe-function-command
   #:buffer-major-mode
   #:list-variables
   #:variable-kind
   #:truncate-value-string
   #:describe-variable-to-string
   #:describe-variable-command

   ;; Describe bindings
   #:*ch-pending*
   #:categorize-command
   #:describe-bindings-to-string
   #:describe-bindings-command

   ;; Type introspection
   #:list-types
   #:type-kind
   #:type-kind-label
   #:type-slot-info
   #:type-struct-slot-info
   #:describe-type-to-string
   #:undocumented-types
   #:describe-type-command

   ;; Known models
   #:*provider-known-models*
   #:provider-known-models
   #:provider-has-token-p
   #:available-models-for-selector

   ;; Prefix processing
   #:*prefix-handlers*
   #:find-prefix-handler
   #:process-prefix-command
   #:shell-prefix-handler

   ;; Debug mode
   #:*debug-mode*
   #:*debug-log-file*
   #:debug-log
   #:file-debug-log
   #:toggle-debug-mode-command
   #:toggle-reasoning-output-command
   #:toggle-metadata-output-command
   #:redraw-screen-command

   ;; Package loader
   #:package-channel
   #:make-package-channel
   #:package-channel-name
   #:package-channel-root
   #:package-channel-description
   #:package-channel-source
   #:package-definition
   #:make-package-definition
   #:package-definition-name
   #:package-definition-description
   #:package-definition-root
   #:package-definition-entrypoint
   #:package-definition-channel
   #:package-definition-source-tier
   #:package-definition-autoload
   #:package-definition-dependencies
   #:package-definition-system-prompt-section
   #:package-definition-prompt-template-directory
   #:package-definition-slash-commands
   #:package-slash-command-spec
   #:make-package-slash-command-spec
   #:package-slash-command-spec-name
   #:package-slash-command-spec-description
   #:package-slash-command-spec-argument-hint
   #:package-slash-command-spec-handler
   #:package-prompt-section
   #:make-package-prompt-section
   #:package-prompt-section-name
   #:package-prompt-section-title
   #:package-prompt-section-package
   #:package-prompt-section-body
   #:*default-package-channel-directory*
   #:*package-channels*
   #:*enabled-builtin-packages*
   #:*package-configuration-path*
   #:*packages-directory*
   #:*current-rplaca-package*
   ;; Package-owned appearance declarations
   #:current-package-appearance-catalog
   #:register-package-appearance-declarations
   #:register-package-appearance-role
   #:register-package-appearance-theme
   #:register-package-appearance-defaults
   #:register-package-channel
   #:list-package-channels
   #:reload-package-channels
   #:list-available-packages
   #:find-available-package
   #:list-installed-packages
   #:find-installed-package
   #:package-install-record-for-definition
   #:package-install-record-source-type
   #:package-install-record-resource-types
   #:package-install-record-scope
   #:package-install-record-project
   #:package-install-record-source
   #:package-install-record-ref
   #:package-install-status-entry
   #:package-status-to-string
   #:package-doctor-report
   #:package-doctor-to-string
   #:install-package-status-string
   #:package-resource-policy-string
   #:remove-installed-package
   #:update-installed-package
   #:set-installed-package-resource-types
   #:package-enablement-scope
   #:set-package-enablement-scope
   #:cycle-package-enablement-scope
   #:active-package-names
   #:package-display-description
   #:package-scope-label
   #:package-scope-message
   #:package-owned-command-metadata
   #:package-owned-tool-metadata
   #:package-owned-prompt-sections
   #:package-owned-buffer-types
   #:package-system-prompt-context-text
   #:maybe-insert-enabled-package-context
   #:describe-installed-package-to-string
   #:open-package-dashboard
   #:load-rplaca-package
   #:load-active-packages
   #:reload-active-packages
   #:load-autoload-packages
   #:register-package-prompt-section
   #:list-package-prompt-sections
   #:render-package-prompt-sections
   #:rplaca-use-package

   ;; User init
   #:*user-init-directory*
   #:*user-init-file*
   #:*inhibit-user-init*
   #:hook-metadata
   #:hook-metadata-name
   #:hook-metadata-args
   #:hook-metadata-docstring
   #:defhook
   #:find-hook-metadata
   #:list-hooks
   #:*startup-hook*
   #:*initial-buffer-hook*
   #:*before-command-hook*
   #:*after-command-hook*
   #:*before-tool-hook*
   #:*after-tool-hook*
   #:*before-send-message-hook*
   #:*after-send-message-hook*
   #:*after-buffer-create-hook*
   #:*after-message-insert-hook*
   #:*after-buffer-display-change-hook*
   #:*after-provider-response-hook*
   #:*package-enablement-changed-hook*
   #:*after-session-save-hook*
   #:*after-session-load-hook*
   #:*session-share-hook*
   #:add-hook
   #:remove-hook
   #:run-hooks
   #:run-hook-with-args
   #:advice-entry
   #:advice-entry-name
   #:advice-entry-where
   #:advice-entry-designator
   #:add-advice
   #:remove-advice
   #:advice-member-p
   #:list-advices
   #:clear-advices
   #:defadvice
   #:load-user-init-file

   ;; McCLIM presentation types
   #:chat-message

   ;; Main
   #:rplaca-main
   #:rplaca-prompt-main
   #:rplaca-session-prompt-main
   #:rplaca-app-server-main
   #:run-single-prompt
   #:run-session-prompt
   #:pipeline-stage
   #:make-pipeline-stage
   #:pipeline-stage-name
   #:pipeline-stage-agent-name
   #:pipeline-stage-prompt
   #:pipeline-stage-next
   #:pipeline-stage-provider
   #:pipeline-stage-model
   #:pipeline-stage-think-level
   #:pipeline-stage-tool-names
   #:pipeline-stage-tool-names-supplied-p
   #:pipeline-stage-package-names
   #:pipeline-stage-skill-names
   #:pipeline-stage-max-tool-iterations
   #:pipeline-stage-output-schema
   #:pipeline-stage-output-parser
   #:pipeline-stage-runner
   #:pipeline-definition
   #:make-pipeline-definition
   #:pipeline-definition-name
   #:pipeline-definition-description
   #:pipeline-definition-stages
   #:pipeline-definition-entry-stage
   #:pipeline-definition-max-steps
   #:pipeline-definition-max-tool-iterations
   #:pipeline-definition-package
   #:pipeline-context
   #:pipeline-context-definition
   #:pipeline-context-original-prompt
   #:pipeline-context-buffer
   #:pipeline-context-stage-results
   #:pipeline-stage-result
   #:pipeline-stage-result-stage-name
   #:pipeline-stage-result-prompt
   #:pipeline-stage-result-result
   #:pipeline-stage-result-parsed-output
   #:pipeline-stage-result-status
   #:pipeline-stage-result-error
   #:pipeline-stage-result-started-at
   #:pipeline-stage-result-finished-at
   #:pipeline-stage-result-final-text
   #:pipeline-stage-result-succeeded-p
   #:pipeline-run-result
   #:pipeline-run-result-pipeline-name
   #:pipeline-run-result-original-prompt
   #:pipeline-run-result-stage-results
   #:pipeline-run-result-final-stage-result
   #:pipeline-run-result-status
   #:pipeline-run-result-error
   #:pipeline-run-result-final-text
   #:define-pipeline
   #:defpipeline
   #:register-pipeline-definition
   #:find-pipeline-definition
   #:list-pipeline-definitions
   #:package-owned-pipeline-definitions
   #:pipeline-test-profile
   #:pipeline-test-profile-name
   #:pipeline-test-profile-description
   #:pipeline-test-profile-command
   #:pipeline-test-profile-package
   #:normalize-pipeline-test-profile-name
   #:define-pipeline-test-profile
   #:register-pipeline-test-profile
   #:find-pipeline-test-profile
   #:list-pipeline-test-profiles
   #:package-owned-pipeline-test-profiles
   #:remove-pipeline-registrations-for-package
   #:pipeline-last-stage-result
   #:pipeline-stage-output
   #:pipeline-stage-parsed-output
   #:run-pipeline-test-profiles
   #:run-pipeline-on-buffer
   #:run-pipeline-prompt
   #:run-pipeline-for-buffer
   #:buffer-has-active-pipeline-p
   #:run-subagent
   #:run-subagent-async
   #:*prompt-max-tool-iterations*
   #:*default-subagent-name*
   #:subagent-handle
   #:subagent-handle-id
   #:subagent-handle-prompt
   #:subagent-handle-agent-name
   #:subagent-handle-status
   #:subagent-handle-result
   #:subagent-handle-error
   #:subagent-handle-started-at
   #:subagent-handle-finished-at
   #:subagent-handle-thread
   #:subagent-handle-cancel-requested-p
   #:find-subagent
   #:list-subagents
   #:active-synchronous-subagent-run-count
   #:subagent-status
   #:subagent-done-p
   #:subagent-result
   #:subagent-error
   #:subagent-snapshot
   #:wait-subagent
   #:cancel-subagent
   #:prompt-run-result
   #:prompt-run-result-prompt
   #:prompt-run-result-final-text
   #:prompt-run-result-tool-events
   #:prompt-run-result-reasoning-blocks
   #:prompt-run-result-structured-output
   #:prompt-run-result-agent-name
   #:prompt-run-result-provider
   #:prompt-run-result-model
   #:prompt-run-result-think-level
   #:prompt-run-result-service-tier
   #:prompt-run-result-iterations
   #:prompt-run-result-stop-reason
   #:prompt-run-result-usage
   #:prompt-run-result-session-name
   #:prompt-run-result-session-id
   #:prompt-run-error
   #:prompt-run-error-message
   #:prompt-run-error-tool-events
   #:prompt-run-error-iterations
   #:prompt-run-error-provider
   #:prompt-run-error-model
   #:prompt-run-error-think-level
   #:prompt-tool-event
   #:prompt-tool-event-id
   #:prompt-tool-event-name
   #:prompt-tool-event-input
   #:prompt-tool-event-result-text
   #:prompt-tool-event-display
   #:prompt-tool-event-denied-p
   #:prompt-run-tool-names
   #:prompt-run-tool-count
   #:prompt-run-used-tool-p
   #:structured-output-validation-error
   #:structured-output-validation-error-schema
   #:structured-output-validation-error-text
   #:structured-output-validation-error-reason
   #:normalize-output-schema
   #:parse-and-validate-structured-output
   #:apply-output-schema-to-prompt-run-result
   #:apply-output-schema-to-pipeline-stage-result
   #:interop-thread
   #:interop-thread-id
   #:interop-thread-buffer
   #:interop-thread-ephemeral-p
   #:interop-thread-created-at
   #:interop-thread-updated-at
   #:interop-thread-current-turn-id
   #:interop-thread-last-result
   #:interop-thread-summary
   #:start-interop-thread
   #:resume-interop-thread
   #:fork-interop-thread
   #:list-interop-threads
   #:active-interop-runtime-operation-count
   #:read-interop-thread
   #:run-interop-thread
   #:interop-turn
   #:interop-turn-id
   #:interop-turn-thread-id
   #:interop-turn-status
   #:interop-turn-input
   #:interop-turn-output-schema
   #:interop-turn-created-at
   #:interop-turn-updated-at
   #:interop-turn-started-at
   #:interop-turn-finished-at
   #:interop-turn-result
   #:interop-turn-error
   #:interop-turn-current-stream-state
   #:interop-turn-interrupt-requested-p
   #:interop-turn-summary
   #:start-interop-turn
   #:read-interop-turn
   #:interrupt-interop-turn
   #:interop-client
   #:make-interop-local-client
   #:interop-client-call
   #:handle-interop-request
   #:send-to-agent-with-context
   #:stop-streaming-response
   #:stop-llm-command
   #:switch-buffer-to-agent
    #:scroll-up-command
    #:scroll-down-command
    #:*scroll-page-size*))
